# Generated by Django 5.1.3 on 2024-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=50)),
                ('IntakeperDivision', models.IntegerField()),
                ('CoursesperDivision', models.IntegerField()),
                ('MaximumIntake', models.IntegerField()),
                ('Division', models.IntegerField()),
                ('Approval', models.CharField(max_length=50)),
            ],
        ),
    ]
