# Generated by Django 5.1.3 on 2024-11-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approval',
            new_name='Approvalmodel',
        ),
    ]
