# Generated by Django 5.1.3 on 2024-11-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0002_rename_approval_approvalmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalmodel',
            old_name='CoursesperDivision',
            new_name='Courses',
        ),
        migrations.RenameField(
            model_name='approvalmodel',
            old_name='IntakeperDivision',
            new_name='Intake',
        ),
        migrations.RenameField(
            model_name='approvalmodel',
            old_name='MaximumIntake',
            new_name='Maximum',
        ),
    ]
