# Generated by Django 5.1.3 on 2024-11-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0003_rename_coursesperdivision_approvalmodel_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
