# Generated by Django 5.1.3 on 2024-11-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0004_approvalmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalmodel',
            name='Approval',
        ),
    ]
